/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export interface external {
  'AcademicCertificateSchema.yaml': {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
    $defs: Record<string, never>;
  };
}

export type operations = Record<string, never>;
